# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

#### Create an array of 10 zeros 

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

#### Create an array of 10 ones

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

#### Create an array of 10 fives

array([ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.])

#### Create an array of the integers from 10 to 50

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

#### Use NumPy to generate a random number between 0 and 1

array([ 0.42829726])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

array([ 1.32031013,  1.6798602 , -0.42985892, -1.53116655,  0.85753232,
        0.87339938,  0.35668636, -1.47491157,  0.15349697,  0.99530727,
       -0.94865451, -1.69174783,  1.57525349, -0.70615234,  0.10991879,
       -0.49478947,  1.08279872,  0.76488333, -2.3039931 ,  0.35401124,
       -0.45454399, -0.64754649, -0.29391671,  0.02339861,  0.38272124])

#### Create the following matrix:

array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

array([ 0.        ,  0.05263158,  0.10526316,  0.15789474,  0.21052632,
        0.26315789,  0.31578947,  0.36842105,  0.42105263,  0.47368421,
        0.52631579,  0.57894737,  0.63157895,  0.68421053,  0.73684211,
        0.78947368,  0.84210526,  0.89473684,  0.94736842,  1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [38]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [39]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE


array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [29]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

20

In [30]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

array([[ 2],
       [ 7],
       [12]])

In [31]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

array([21, 22, 23, 24, 25])

In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

325

#### Get the standard deviation of the values in mat

7.2111025509279782

#### Get the sum of all the columns in mat

array([55, 60, 65, 70, 75])

# Mathematical functions

In [2]:
import numpy as np

In [3]:
np.__version__

'1.17.4'

## Trigonometric functions

Q1. Calculate sine, cosine, and tangent of x, element-wise.

In [4]:
x = np.array([0., 1., 30, 90])


Q2. Calculate inverse sine, inverse cosine, and inverse tangent of x, element-wise.

In [31]:
x = np.array([-1., 0, 1.])


inverse sine: [ 1.57079633  0.          1.57079633]
inverse cosine: [ 0.          1.57079633  0.        ]
inverse tangent: [ 0.78539816  0.          0.78539816]


Q3. Convert angles from radians to degrees.

In [45]:
x = np.array([-np.pi, -np.pi/2, np.pi/2, np.pi])


[-180.  -90.   90.  180.]


Q4. Convert angles from degrees to radians.

In [48]:
x = np.array([-180.,  -90.,   90.,  180.])


[-3.14159265 -1.57079633  1.57079633  3.14159265]


## Rounding

Q6. Predict the results of these, paying attention to the difference among the family functions.

In [3]:
x = np.array([2.1, 1.5, 2.5, 2.9, -2.1, -2.5, -2.9])

out1 = np.around(x)
out2 = np.floor(x)
out3 = np.ceil(x)
out4 = np.trunc(x)
out5 = [round(elem) for elem in x]



Q7. Implement out5 in the above question using numpy.

[ 2.  2.  3.  3. -2. -3. -3.]


## Sums, products, differences

Q8. Predict the results of these.

In [5]:
x = np.array(
    [[1, 2, 3, 4],
     [5, 6, 7, 8]])

outs = [np.sum(x),
        np.sum(x, axis=0),
        np.sum(x, axis=1, keepdims=True),
        "",
        np.prod(x),
        np.prod(x, axis=0),
        np.prod(x, axis=1, keepdims=True),
        "",
        np.cumsum(x),
        np.cumsum(x, axis=0),
        np.cumsum(x, axis=1),
        "",
        np.cumprod(x),
        np.cumprod(x, axis=0),
        np.cumprod(x, axis=1),
        "",
        np.min(x),
        np.min(x, axis=0),
        np.min(x, axis=1, keepdims=True),
        "",
        np.max(x),
        np.max(x, axis=0),
        np.max(x, axis=1, keepdims=True),
        "",
        np.mean(x),
        np.mean(x, axis=0),
        np.mean(x, axis=1, keepdims=True)]
           
for out in outs:
    if out == "":
        pass
        print()
    else:
        pass
        print("->", out)


/Users/ddl/anaconda3/envs/datascience/lib/python3.6/site-packages/ipykernel_launcher.py:34: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison


Q9. Calculate the difference between neighboring elements, element-wise.

In [100]:
x = np.array([1, 2, 4, 7, 0])


[ 1  2  3 -7]


Q10. Calculate the difference between neighboring elements, element-wise, and
prepend [0, 0] and append[100] to it.

In [108]:
x = np.array([1, 2, 4, 7, 0])


[  0   0   1   2   3  -7 100]


Q11. Return the cross product of x and y.

In [110]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])



[-3  6 -3]


## Exponents and logarithms

Q12. Compute $e^x$, element-wise.

In [115]:
x = np.array([1., 2., 3.], np.float32)



[  2.71828175   7.38905621  20.08553696]


Q13. Calculate exp(x) - 1 for all elements in x.

In [118]:
x = np.array([1., 2., 3.], np.float32)


[  1.71828175   6.38905621  19.08553696]


Q14. Calculate $2^p$ for all p in x.

In [124]:
x = np.array([1., 2., 3.], np.float32)


[ 2.  4.  8.]


Q15. Compute natural, base 10, and base 2 logarithms of x element-wise.

In [128]:
x = np.array([1, np.e, np.e**2])


natural log = [ 0.  1.  2.]
common log = [ 0.          0.43429448  0.86858896]
base 2 log = [ 0.          1.44269504  2.88539008]


## Arithmetic operations

Q19. Add x and y element-wise.

In [141]:
x = np.array([1, 2, 3])
y = np.array([-1, -2, -3])



[0 0 0]


Q20. Subtract y from x element-wise.

In [142]:
x = np.array([3, 4, 5])
y = np.array(3)



[0 1 2]


Q21. Multiply x by y element-wise.

In [144]:
x = np.array([3, 4, 5])
y = np.array([1, 0, -1])



[ 3  0 -5]


Q22. Divide x by y element-wise in two different ways.

In [161]:
x = np.array([3., 4., 5.])
y = np.array([1., 2., 3.])


[ 3.          2.          1.66666667]
[ 3.  2.  1.]


Q23. Compute numerical negative value of x, element-wise.

In [146]:
x = np.array([1, -1])


[-1  1]


Q24. Compute the reciprocal of x, element-wise.

In [155]:
x = np.array([1., 2., .2])


[ 1.   0.5  5. ]


Q25. Compute $x^y$, element-wise.

In [163]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[1, 2], [1, 2]])


[[ 1  4]
 [ 3 16]]


Q26. Compute the remainder of x / y element-wise in two different ways.

In [168]:
x = np.array([-3, -2, -1, 1, 2, 3])
y = 2


[1 0 1 1 0 1]
[-1  0 -1  1  0  1]


# Logic functions

In [1]:
import numpy as np

In [2]:
np.__version__

'1.11.2'

## Truth value testing


Q1. Let x be an arbitrary array. Return True if none of the elements of x is zero. Remind that 0 evaluates to False in python.


In [4]:
x = np.array([1,2,3])
#

x = np.array([1,0,3])
#

True
False


Q2. Let x be an arbitrary array. Return True if any of the elements of x is non-zero.

In [5]:
x = np.array([1,0,0])
#

x = np.array([0,0,0])
#

True
False


## Array contents


Q3. Predict the result of the following code.

In [8]:
x = np.array([1, 0, np.nan, np.inf])
#print np.isfinite(x)

Q4. Predict the result of the following code.

In [10]:
x = np.array([1, 0, np.nan, np.inf])
#print np.isinf(x)

Q5. Predict the result of the following code.

In [12]:
x = np.array([1, 0, np.nan, np.inf])
#print np.isnan(x)

## Array type testing

Q6. Predict the result of the following code.

In [15]:
x = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
#print np.iscomplex(x)

Q7. Predict the result of the following code.

In [18]:
x = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
#print np.isreal(x)

Q8. Predict the result of the following code.

In [21]:
#print np.isscalar(3)
#print np.isscalar([3])
#print np.isscalar(True)

## Logical operations

Q9. Predict the result of the following code.

In [31]:
#print np.logical_and([True, False], [False, False])
#print np.logical_or([True, False, True], [True, False, False])
#print np.logical_xor([True, False, True], [True, False, False])
#print np.logical_not([True, False, 0, 1])


## Comparison

Q10. Predict the result of the following code.

In [42]:
#print np.allclose([3], [2.999999])
#print np.array_equal([3], [2.999999])

Q11. Write numpy comparison functions such that they return the results as you see.

In [51]:
x = np.array([4, 5])
y = np.array([2, 5])
#
#
#
#

[ True False]
[ True  True]
[False False]
[False  True]


Q12. Predict the result of the following code.

In [50]:
#print np.equal([1, 2], [1, 2.000001])
#print np.isclose([1, 2], [1, 2.000001])

## Boolean operations

Q2. Create a boolean array of the same shape as x. If each element of x is present in y, the result will be True, otherwise False.

In [19]:
x = np.array([0, 1, 2, 5, 0])
y = np.array([0, 1])


[ True  True False False  True]


Q3. Find the unique intersection of x and y.

In [20]:
x = np.array([0, 1, 2, 5, 0])
y = np.array([0, 1, 4])


[0 1]


Q4. Find the unique elements of x that are not present in y.

In [21]:
x = np.array([0, 1, 2, 5, 0])
y = np.array([0, 1, 4])


[2 5]


Q5. Find the xor elements of x and y.

In [40]:
x = np.array([0, 1, 2, 5, 0])
y = np.array([0, 1, 4])


[2 4 5]


Q6. Find the union of x and y.

In [42]:
x = np.array([0, 1, 2, 5, 0])
y = np.array([0, 1, 4])


[0 1 2 4 5]


# Searching, and counting

## Searching

Q6. Get the maximum and minimum values and their indices of x along the second axis.

In [ ]:
x = np.random.permutation(10).reshape(2, 5)
print("x =", x)


Q7. Get the maximum and minimum values and their indices of x along the second axis, ignoring NaNs.

In [79]:
x = np.array([[np.nan, 4], [3, 2]])


maximum values ignoring NaNs = [ 4.  3.]
max indices = [1 0]
minimum values ignoring NaNs = [ 4.  2.]
min indices = [1 1]


Q8. Get the values and indices of the elements that are bigger than 2 in x.


In [113]:
x = np.array([[1, 2, 3], [1, 3, 5]])


Values bigger than 2 = [3 3 5]
Their indices are  (array([0, 1, 1], dtype=int64), array([2, 1, 2], dtype=int64))


Q9. Get the indices of the elements that are bigger than 2 in the flattend x.

In [100]:
x = np.array([[1, 2, 3], [1, 3, 5]])


[0 1 2 3 4 5]


Q10. Check the elements of x and return 0 if it is less than 0, otherwise the element itself.

In [105]:
x = np.arange(-5, 4).reshape(3, 3)


[[0 0 0]
 [0 0 0]
 [1 2 3]]


Q11. Get the indices where elements of y should be inserted to x to maintain order.

In [109]:
x = [1, 3, 5, 7, 9]
y = [0, 4, 2, 6]


array([0, 2, 1, 3], dtype=int64)

## Counting

Q12. Get the number of nonzero elements in x.

In [120]:
x = [[0,1,7,0,0],[3,0,0,2,19]]


5


In [3]:
Ejercicios tomados de:
    

__author__ = "kyubyong. kbpark.linguist@gmail.com. https://github.com/kyubyong"