## Matrix Operations and Functions

### Arithmetic Operations

Recall that arithmetic [array operations](../scipy/numpy/#operations-and-functions) `+`, `-`, `/`, `*` and `**` are performed elementwise on NumPy arrays. Let's create a NumPy array and do some computations:

In [0]:
M = np.array([[3,4],[-1,5]])
print(M)

[[ 3  4]
 [-1  5]]


Calcular M * M


array([[ 9, 16],
       [ 1, 25]])

### Matrix Multiplication

Use the `@` operator to do matrix multiplication with NumPy arrays for M :

array([[ 5, 32],
       [-8, 21]])

Let's compute $2I + 3A - AB$ for

$$
A = \begin{bmatrix}
1 & 3 \\\
-1 & 7
\end{bmatrix}
\ \ \ \
B = \begin{bmatrix}
5 & 2 \\\
1 & 2
\end{bmatrix}
$$

and $I$ is the identity matrix of size 2:

In [0]:
2*I + 3*A - A@B

array([[-3.,  1.],
       [-5., 11.]])

###  Tranpose

We can take the transpose with `.T` attribute:

In [0]:
print(M)

[[ 3  4]
 [-1  5]]


Calcular la traspuesta de M

[[ 3 -1]
 [ 4  5]]


Calculate  $M M^T$ :

array([[25, 17],
       [17, 26]])

### Inverse

We can find the inverse using the function `scipy.linalg.inv`:

In [0]:
A = np.array([[1,2],[3,4]])
print(A)

[[1 2]
 [3 4]]


Calcular la inversa de A

### Trace

We can find the trace of a matrix using the function `numpy.trace`:

5


### Determinant

We find the determinant using the function `scipy.linalg.det`:

In [0]:
A = np.array([[1,2],[3,4]])
print(A)

[[1 2]
 [3 4]]


Calcular el determinante de A